"""Generate kbd/kbd_font.h (8x12 bitmap font, ASCII + Portuguese accents) from a font installed on YOUR Windows machine.
Run:  python kbd/make_font.py   (calls genfont.ps1, which uses System.Drawing). The generated header is git-ignored:
glyph bitmaps rendered from a proprietary font (the default is Consolas) must not be redistributed; pick a font whose licence allows it."""
import json, os, subprocess
H = os.path.dirname(os.path.abspath(__file__))
subprocess.run(['powershell', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', os.path.join(H, 'genfont.ps1')], check=True)
f = json.load(open(os.path.join(H, 'font8x12.json')))
cps = sorted(int(k) for k in f); ascii_ = [c for c in cps if 32 <= c <= 126]; extra = [c for c in cps if c > 126]
assert ascii_ == list(range(32, 127))
out = ['/* generated by make_font.py */', '#ifndef KBD_FONT_H', '#define KBD_FONT_H', '#include <stdint.h>',
       'static const uint16_t kbd_font_extra_cp[%d] = {%s};' % (len(extra), ','.join(map(str, extra))), 'static const uint8_t kbd_font[%d][12] = {' % len(cps)]
for c in ascii_ + extra: out.append('    {%s}, /* %d */' % (','.join('0x%02x' % b for b in f[str(c)]), c))
out += ['};', '#define KBD_FONT_N_ASCII 95', '#endif']
open(os.path.join(H, 'kbd_font.h'), 'w').write('\n'.join(out) + '\n'); print('wrote kbd_font.h', len(cps), 'glyphs')
