/* ================= Internet over Bluetooth tethering (PAN / BNEP) for the web reader =================
 * Included by webreader.inc.c when built with -DNET_APP. The phone shares its internet over Bluetooth (the "NAP" role); the watch is the PANU.
 *   1. l2cap_open() to the phone, PSM 0x000F (BNEP), run in the Bluetooth thread through app_bt_call_func_in_bt_thread()
 *   2. net/netstack.c: BNEP handshake, DHCP, ARP, DNS, TCP and an encrypted channel (ChaCha20-Poly1305) to webbridge/proxy.js
 *   3. the proxy fetches the page (HTTPS included) and returns the reader's text format
 * The L2CAP callbacks run in the Bluetooth thread and have no user context, so they find the state through the LVGL timer list (our reader timer's
 * user_data is the WR*); received frames are queued there and consumed by the GUI-thread timer. No writable globals (flash cave is read-only).
 * Firmware addresses were found by static analysis (see memory notes); everything is overridable for host tests. */
#include "chacha.c"
#include "netstack.c"
#include "net_cfg.h"                      /* generated by build2.py --net: NET_PROXY_HOST, NET_PROXY_PORT, NET_PSK */

#ifndef BT_CALL
#define BT_CALL ((int (*)(u32, u32, u32, u32, void *))0x2c2339e9)          /* app_bt_call_func_in_bt_thread(p0,p1,p2,p3,func) */
#endif
#ifndef L2CAP_OPEN
#define L2CAP_OPEN ((u32 (*)(const u8 *, u32, u32, u32, void *, void *))0x2c25fd51)   /* (bdaddr*, psm, mode, mtu, event_cb, data_cb) -> channel* */
#endif
#ifndef L2CAP_SEND
#define L2CAP_SEND ((u32 (*)(u32, const void *, u32, u32))0x2c2607f5)      /* l2cap_send_data_auto_fragment(handle, data, len, tag) -> 0 ok */
#endif
#ifndef L2CAP_CLOSE
#define L2CAP_CLOSE ((void (*)(u32, u32, u32))0x2c25ee45)                  /* l2cap_channel_close(?, channel*, reason) */
#endif
#ifndef PPB_DATA
#define PPB_DATA ((u8 *(*)(void *))0x2c250541)                             /* data pointer of a received packet buffer; length = u16 at +8 */
#endif
#ifndef BT_DEV
#define BT_DEV(i) ((u8 *)(0x2011c1d0u + (u32)(i) * 0x124u))                /* app_bt device struct: bd_addr[6] at +0, in-use flag at +6 */
#endif
#ifndef LV_TIMER_LL
#define LV_TIMER_LL ((u32 *)0x201345d8)                                    /* lv_ll_t of timers: [0]=node size, [1]=head */
#endif

#ifndef P2U                                   /* pointer <-> 32-bit job parameter (identity on the watch; host tests map through a table) */
#define P2U(p) ((u32)(p))
#define U2P(u) ((void *)(u))
#endif
#define NG_RQ 8
#define NG_RQLEN 640
enum { NP_IDLE, NP_OPEN, NP_NET, NP_SC, NP_READY, NP_FAIL };
typedef struct NG {
    Net *net; u32 chan, handle; volatile u8 opened, closed, job_err; volatile u32 last_ev; volatile u32 drops;
    u8 phase, dev, have_pending, retried, welcomed, sc_try; u32 t0, req_t0, rng; char err[64]; char pending[200];
    u8 rq[NG_RQ][NG_RQLEN]; volatile u16 rlen[NG_RQ]; volatile u8 rh, rt;
    int resp_len; u8 resp_on; u8 mb[SC_MSG_MAX + 8]; u32 last_draw; u8 last_phase, last_net, last_sc;
} NG;

static void wr_tick(void *timer);

#ifndef NG_FIND_CTX
/* Bluetooth-thread context lookup: walk LVGL's timer list for our reader timer; its user_data is the WR whose ng we need. */
static void *ng_find_wr(void) {
    u32 *ll = LV_TIMER_LL; u32 nsz = ll[0]; u8 *t = (u8 *)ll[1];
    for (int i = 0; t && i < 64; i++) { if (*(u32 *)(t + 8) == (u32)(void *)wr_tick) return *(void **)(t + 0xC); t = *(u8 **)(t + nsz + 4); }
    return 0;
}
#define NG_FIND_CTX() ng_find_wr()
#endif

/* ---- Bluetooth-thread side ---- */
static void ng_event(void *mgr, u32 ev, u32 handle, void *c, u32 x);
static void ng_data(void *mgr, u32 handle, void *pb);
static void job_open(u32 gp, u32 psm, u32 mtu, u32 unused);
static void job_send(u32 handle, u32 buf, u32 len, u32 unused);
static void job_close(u32 chan, u32 a, u32 b, u32 c);

/* ---- GUI-thread side ---- */
static void ng_fail(NG *g, const char *msg) { int i = 0; while (msg[i] && i < 62) { g->err[i] = msg[i]; i++; } g->err[i] = 0; g->phase = NP_FAIL; }
static void ng_tx(void *ctx, const u8 *sdu, int len) {
    NG *g = (NG *)ctx; if (!g->handle || g->closed || len <= 0 || len > 1700) return;
    u8 *b = (u8 *)MALLOC((u32)len); if (!b) return;
    for (int i = 0; i < len; i++) b[i] = sdu[i];
    BT_CALL(g->handle, P2U(b), (u32)len, 0, (void *)job_send);                  /* the job frees b */
}
static uint32_t ng_now(void *ctx) { (void)ctx; return TICK_GET(); }
static void ng_rnd(void *ctx, u8 *o, int n) {
    NG *g = (NG *)ctx;
    for (int i = 0; i < n; i++) { g->rng ^= g->rng << 13; g->rng ^= g->rng >> 17; g->rng ^= g->rng << 5; g->rng += TICK_GET() * 2654435761u; o[i] = (u8)(g->rng >> 11); }
}
static int ng_start(NG *g) {
    int dev = -1;
    for (int i = 0; i < 2; i++) { const u8 *d = BT_DEV(i); if (d[6] && (d[0] | d[1] | d[2] | d[3] | d[4] | d[5])) { dev = i; break; } }
    if (dev < 0) { ng_fail(g, TR("Celular nao conectado por Bluetooth", "Phone not connected over Bluetooth")); return 0; }
    g->dev = (u8)dev; const u8 *d = BT_DEV(dev);
    { u8 mac[6] = { 0x02, 0xF1, 0x7A, d[3], d[4], (u8)(d[5] ^ 0x5A) }; NetOps ops = { ng_tx, ng_now, ng_rnd, g }; net_init(g->net, &ops, mac); }
    g->opened = g->closed = g->job_err = 0; g->handle = 0; g->chan = 0; g->rh = g->rt = 0; g->last_ev = 0; g->err[0] = 0; g->sc_try = 0;
    g->resp_on = 0; g->resp_len = 0; g->t0 = TICK_GET(); g->phase = NP_OPEN;
    BT_CALL(P2U(g), 0x000F, 1691, 0, (void *)job_open);                         /* BNEP PSM, MTU >= 1691 as the spec requires */
    return 1;
}
static void ng_stop(NG *g) {
    if (g->chan && !g->closed) { BT_CALL(g->chan, 0, 0, 0, (void *)job_close); }
    g->chan = 0; g->handle = 0; g->phase = NP_IDLE;
}
static void ng_ip_str(u32 ip, char *o) {                                   /* dotted IPv4 into o[16] */
    int k = 0;
    for (int b = 3; b >= 0; b--) { int v = (int)((ip >> (8 * b)) & 255); char d[4]; int l = 0; do { d[l++] = (char)('0' + v % 10); v /= 10; } while (v); while (l) o[k++] = d[--l]; if (b) o[k++] = '.'; }
    o[k] = 0;
}
static void ng_connect_proxy(NG *g) {
    static const u8 psk[32] = NET_PSK;
    const char *host = NET_PROXY_HOST; char gws[20];
    if (host[0] == 'g' && host[1] == 'w' && host[2] == 0) { ng_ip_str(g->net->gw ? g->net->gw : g->net->dns, gws); host = gws; }   /* "gw": the phone itself (the tethering gateway) runs the proxy */
    if (sc_connect(g->net, host, NET_PROXY_PORT, psk) < 0) ng_fail(g, TR("Nao foi possivel iniciar o proxy", "Could not start the proxy connection"));
    else { g->phase = NP_SC; g->t0 = TICK_GET(); g->sc_try++; }
}

static void ng_request(WR *w, const char *q) {
    NG *g = (NG *)w->ng; int n = 0; while (q[n] && n < 190) { g->pending[n] = q[n]; n++; } g->pending[n] = 0;
    g->have_pending = 1; g->retried = 0; g->req_t0 = TICK_GET(); g->resp_on = 0; g->resp_len = 0; g->welcomed = 1;   /* a page is coming: never show the welcome text over it */
    if (g->phase == NP_FAIL) { g->t0 = TICK_GET(); g->phase = NP_IDLE; }
    w->mode = WM_WAIT; w->dirty = 1;
}
static void ng_page_error(WR *w, const char *pt, const char *en) { wr_set_text(w, TR("Erro", "Error"), TR(pt, en)); }

/* One 50 ms step of the whole pipeline. */
static void ng_tick(WR *w) {
    NG *g = (NG *)w->ng; u32 now = TICK_GET(); Net *net = g->net;
    while (g->rt != g->rh) { u8 s = g->rt; net_link_rx(net, g->rq[s], g->rlen[s]); g->rt = (u8)((s + 1) % NG_RQ); }
    switch (g->phase) {
    case NP_IDLE: if (now - g->t0 >= 1000u || g->t0 == 0) ng_start(g); break;
    case NP_OPEN:
        if (g->job_err) ng_fail(g, TR("O canal Bluetooth de rede foi recusado", "The Bluetooth network channel was refused"));
        else if (g->opened) { net_link_up(net); g->phase = NP_NET; g->t0 = now; }
        else if (g->closed) ng_fail(g, TR("O celular fechou o canal de rede (ancoragem ligada?)", "The phone closed the network channel (tethering on?)"));
        else if (now - g->t0 > 15000u) ng_fail(g, TR("Sem resposta do celular (ligue a ancoragem Bluetooth)", "No answer from the phone (turn on Bluetooth tethering)"));
        break;
    case NP_NET:
        net_tick(net);
        if (net->state == NS_READY) ng_connect_proxy(g);
        else if (net->state == NS_FAIL) ng_fail(g, net->bnep_ok ? TR("Sem endereco IP (DHCP/ARP falhou)", "No IP address (DHCP/ARP failed)") : TR("O celular recusou o BNEP", "The phone refused BNEP"));
        else if (g->closed) ng_fail(g, TR("O canal Bluetooth foi fechado", "The Bluetooth channel was closed"));
        break;
    case NP_SC:
        net_tick(net);
        if (net->sc.state == SC_READY) { g->phase = NP_READY; g->t0 = now; }
        else if (net->sc.state == SC_ERR || now - g->t0 > 25000u) ng_fail(g, TR("Proxy inacessivel ou chave errada", "Proxy unreachable or wrong key"));
        break;
    case NP_READY: {
        net_tick(net);
        if (g->closed) { ng_fail(g, TR("O canal Bluetooth foi fechado", "The Bluetooth channel was closed")); break; }
        if (net->sc.state != SC_READY) {                                                      /* dropped: reconnect on demand */
            if (g->have_pending || g->resp_on) { if (net->sc.state == SC_ERR || net->sc.state == SC_IDLE) { net->tcp.state = TCP_CLOSED; ng_connect_proxy(g); } }
            break;
        }
        if (!g->welcomed && !g->have_pending && !g->resp_on) {
            g->welcomed = 1;
            if (w->netmode == 2) wr_set_text(w, "IA", TR("Pergunte qualquer coisa.\n\nToque em Ir, digite a pergunta no teclado T9 e confirme com OK. A resposta aparece aqui; arraste para rolar. Perguntas seguintes lembram a conversa.\n\nA chave do Groq fica so no PC.",
                "Ask anything.\n\nTap Go, type your question on the T9 keyboard and confirm with OK. The answer shows up here; drag to scroll. Follow-up questions remember the conversation.\n\nThe Groq key stays on the PC only."));
            else wr_set_text(w, TR("Internet", "Internet"), TR("Conectado pela ancoragem Bluetooth do celular.\n\nToque em Ir, digite um endereco (ex.: example.com) ou uma busca e confirme com OK.\n\nToque em um [n] para abrir um link. Arraste para rolar. L lista os links; < volta.",
                "Connected through your phone's Bluetooth tethering.\n\nTap Go, type an address (e.g. example.com) or a search and confirm with OK.\n\nTap a [n] to open a link. Drag to scroll. L lists the links; < goes back."));
            w->mode = w->netmode == 3 ? WM_DIAL : WM_PAGE; MOTOR_ONCE(1, 0);
        }
        if (g->have_pending) {
            u8 m[200]; int l = 0; m[l++] = (u8)(w->netmode == 2 ? 'A' : w->netmode == 3 ? 'D' : 'G');           /* 'A' = ask the Groq AI, 'G' = fetch a page */ for (int i = 0; g->pending[i] && l < 199; i++) m[l++] = (u8)g->pending[i];
            if (sc_send(net, m, l) == 0) { g->have_pending = 0; g->resp_on = 1; g->resp_len = 0; g->req_t0 = now; }
        }
        if (g->resp_on) {
            int r;
            while ((r = sc_recv(net, g->mb, SC_MSG_MAX + 8)) > 0) {
                int n = r - 1;
                if (n > 0 && g->resp_len + n < WR_BUF - 8) { for (int i = 0; i < n; i++) w->buf[g->resp_len + i] = g->mb[1 + i]; g->resp_len += n; }
                if (g->mb[0] == 1) {                                                          /* last chunk */
                    g->resp_on = 0; w->buf[g->resp_len] = 0; w->len = g->resp_len;
                    if (g->resp_len > 0 && w->buf[0] == '!') { wr_set_text(w, TR("Erro do proxy", "Proxy error"), (const char *)w->buf + 1); }
                    else if (wr_parse(w, 0)) { w->mode = WM_PAGE; MOTOR_ONCE(1, 0); }
                    else ng_page_error(w, "Resposta invalida do proxy.", "Invalid answer from the proxy.");
                    w->dirty = 1; break;
                }
            }
            if (r < 0) { g->resp_on = 0; if (!g->retried) { g->retried = 1; g->have_pending = 1; } else ng_page_error(w, "A conexao com o proxy caiu.", "The proxy connection dropped."); }
            if (g->resp_on && now - g->req_t0 > 60000u) { g->resp_on = 0; ng_page_error(w, "O proxy nao respondeu em 60 s.", "The proxy did not answer in 60 s."); w->dirty = 1; }
        }
        break; }
    default: break;
    }
    if (g->phase != g->last_phase || net->state != g->last_net || net->sc.state != g->last_sc || (w->mode == WM_WAIT && now - g->last_draw > 350u)) {
        g->last_phase = g->phase; g->last_net = net->state; g->last_sc = net->sc.state; g->last_draw = now; w->dirty = 1;
    }
}

static void ng_num(u16 *g, int x, int y, int v) { mg_num(g, x, y, v, 1, C(150, 160, 190)); }
/* Status screen: four steps, so a failure shows exactly where it stopped. */
static void ng_draw_status(WR *w, u16 *g) {
    NG *n = (NG *)w->ng; Net *net = n->net;
    int done[4]; done[0] = n->phase >= NP_OPEN && n->phase != NP_IDLE; done[1] = net->bnep_ok && n->phase >= NP_NET; done[2] = net->state == NS_READY && n->phase >= NP_NET; done[3] = net->sc.state == SC_READY;
    if (n->phase == NP_FAIL && net->state != NS_READY) { if (!n->opened) done[0] = n->dev < 2 && BT_DEV(n->dev)[6] ? 1 : 0; }
    int cur = 0; while (cur < 4 && done[cur]) cur++;
    static const char *pt[4] = { "Celular (Bluetooth)", "Canal de rede (BNEP)", "Endereco IP (DHCP)", "Proxy seguro" };
    static const char *en[4] = { "Phone (Bluetooth)", "Network link (BNEP)", "IP address (DHCP)", "Secure proxy" };
    for (int i = 0; i < 4; i++) {
        int y = 40 + i * 38; uint16_t dot = done[i] ? C(80, 200, 130) : (i == cur ? (n->phase == NP_FAIL ? C(230, 90, 100) : C(240, 190, 80)) : C(90, 96, 120));
        rrect(g, 8, y, 240, 32, 12, C(28, 32, 52));
        disc(g, 28, y + 16, 9, dot);
        if (done[i]) { rect(g, 24, y + 16, 3, 5, C(12, 14, 22)); rect(g, 27, y + 12, 3, 9, C(12, 14, 22)); }
        else if (i == cur && n->phase != NP_FAIL) { int ph = (int)((TICK_GET() / 250u) % 4u); disc(g, 28 + (ph == 1) * 4 - (ph == 3) * 4, y + 16 - (ph == 0) * 4 + (ph == 2) * 4, 3, C(12, 14, 22)); }
        else if (i == cur) { rect(g, 25, y + 15, 7, 3, C(12, 14, 22)); }
        draw_wrapped(g, TR(pt[i], en[i]), 46, y + 10, 1, 24, 1, 0, done[i] ? C(235, 235, 240) : C(170, 175, 195), 0);
    }
    if (net->state == NS_READY) { char ip[24]; int k = 0; for (int b = 3; b >= 0; b--) { int v = (int)((net->ip >> (8 * b)) & 255); char d[4]; int l = 0; do { d[l++] = (char)('0' + v % 10); v /= 10; } while (v); while (l) ip[k++] = d[--l]; if (b) ip[k++] = '.'; } ip[k] = 0; draw_wrapped(g, ip, 46, 194, 1, 20, 1, 0, C(90, 200, 255), 0); }
    if (n->phase == NP_FAIL) {
        draw_wrapped(g, n->err, 10, 214, 1, 30, 4, 0, C(255, 130, 130), 0);
        draw_wrapped(g, TR("Toque na tela para tentar de novo.", "Tap the screen to try again."), 10, 262, 1, 30, 2, 0, C(235, 235, 240), 0);
    } else if (n->phase == NP_READY) {
        draw_wrapped(g, n->have_pending || n->resp_on ? TR("Buscando a pagina...", "Loading the page...") : "", 10, 214, 1, 30, 2, 0, C(255, 210, 90), 0);
    }
    /* diagnostics, so a report from the watch is enough to find the problem */
    ptext(g, 8, 330, "ev", 1, C(120, 128, 150)); ng_num(g, 24, 330, (int)n->last_ev); ptext(g, 48, 330, "ph", 1, C(120, 128, 150)); ng_num(g, 64, 330, n->phase);
    ptext(g, 80, 330, "net", 1, C(120, 128, 150)); ng_num(g, 104, 330, net->state); ptext(g, 120, 330, "tcp", 1, C(120, 128, 150)); ng_num(g, 144, 330, net->tcp.state);
    ptext(g, 160, 330, "sc", 1, C(120, 128, 150)); ng_num(g, 176, 330, net->sc.state); ptext(g, 192, 330, "rx", 1, C(120, 128, 150)); ng_num(g, 208, 330, (int)n->drops);
}

/* ---- Bluetooth-thread functions ---- */
static void ng_event(void *mgr, u32 ev, u32 handle, void *c, u32 x) {
    (void)mgr; (void)c; (void)x; WR *w = (WR *)NG_FIND_CTX(); if (!w || !w->ng) return; NG *g = (NG *)w->ng;
    g->last_ev = ev;
    if (ev == 1) { g->handle = handle; g->opened = 1; } else if (ev == 4) g->closed = 1;
}
static void ng_data(void *mgr, u32 handle, void *pb) {
    (void)mgr; (void)handle; WR *w = (WR *)NG_FIND_CTX(); if (!w || !w->ng || !pb) return; NG *g = (NG *)w->ng;
    u32 len = *(u16 *)((u8 *)pb + 8);
    if (len == 0 || len > NG_RQLEN) { g->drops++; return; }
    u8 nh = (u8)((g->rh + 1) % NG_RQ); if (nh == g->rt) { g->drops++; return; }
    const u8 *src = PPB_DATA(pb); u8 *dst = g->rq[g->rh]; for (u32 i = 0; i < len; i++) dst[i] = src[i];
    g->rlen[g->rh] = (u16)len; g->rh = nh;
}
static void job_open(u32 gp, u32 psm, u32 mtu, u32 unused) {
    (void)unused; NG *g = (NG *)U2P(gp); const u8 *dev = BT_DEV(g->dev);
    g->chan = L2CAP_OPEN(dev, psm, 0, mtu, (void *)ng_event, (void *)ng_data);
    if (!g->chan) g->job_err = 1;
}
static void job_send(u32 handle, u32 buf, u32 len, u32 unused) { (void)unused; L2CAP_SEND(handle, U2P(buf), len, 0); FREE(U2P(buf)); }
static void job_close(u32 chan, u32 a, u32 b, u32 c) { (void)a; (void)b; (void)c; L2CAP_CLOSE(0, chan, 0x13); }
