/* Voxel "block world" engine (original code): terrain generation, 14 block types, creative flight, picking, mesh + procedural textures.
 * Portable, no libc beyond what rdmath.h provides; no globals (the cave is read-only flash): everything lives in a caller-allocated Vox. */
#ifndef VOX_H
#define VOX_H
#include <stdint.h>
#include "m3d.h"

#define VX_W 64            /* x */
#define VX_D 64            /* z */
#define VX_H 40            /* y (up) */
#define VX_TILES 17
#define VX_TEXW (VX_TILES * 16)

enum { VB_AIR, VB_GRASS, VB_DIRT, VB_STONE, VB_COBBLE, VB_SAND, VB_LOG, VB_PLANKS, VB_LEAVES, VB_BRICK, VB_GLASS, VB_WOOL_R, VB_WOOL_B, VB_SNOW, VB_COAL, VB_BEDROCK, VB_N };
#define VB_PLACEABLE 14    /* ids 1..14 can be put in the hotbar */
enum { VK_FWD, VK_BACK, VK_LEFT, VK_RIGHT, VK_UP, VK_DOWN, VK_N };
enum { VW_HILLS, VW_FLAT, VW_MOUNTAINS, VW_DESERT, VW_TYPES };

typedef struct { int x, y, z, f; } VxHit;
typedef struct {
    uint8_t blk[VX_W * VX_H * VX_D];
    uint8_t top[VX_W * VX_D];                 /* highest non-air y of each column (for the shade of covered cells) */
    float x, y, z, xo, yo, zo, xd, yd, zd, yaw, pitch;   /* x,y,z = eye */
    int on_ground, flying, has_hit, radius, sel, ticks, modified, wtype;
    uint8_t held[VK_N], hot[9];
    float turn_yaw, turn_pitch, passed, alpha;
    int64_t last_ms;
    uint32_t seed;
    VxHit hit;
} Vox;

void vx_gen(Vox *g, uint32_t seed, int type);       /* new world + player on the surface near the middle */
void vx_key(Vox *g, int key, int down);
void vx_look(Vox *g, float dx, float dy);            /* camera turn in "key units": 0.15 degrees each */
void vx_tick(Vox *g);
void vx_advance(Vox *g, int64_t now_ms);             /* sets g->ticks (60 per second) and g->alpha */
int  vx_break(Vox *g);                               /* 1 if a block was removed */
int  vx_place(Vox *g);                               /* puts the selected hotbar block against the targeted face; 1 if done */
void vx_recalc_tops(Vox *g);
#define VX_IDX(x, y, z) (((y) * VX_D + (z)) * VX_W + (x))
#define vx_get(g, x, y, z) ((x) >= 0 && (y) >= 0 && (z) >= 0 && (x) < VX_W && (y) < VX_H && (z) < VX_D ? (g)->blk[VX_IDX(x, y, z)] : 0)
void vx_toggle_fly(Vox *g);
void vx_make_tex(uint16_t *pix);                    /* VX_TEXW x 16 RGB565 atlas, generated by code */
void vx_render(const Vox *g, const M3dTex *tex, int w, int h, uint16_t *fb, uint16_t *zb);
int vx_face_tile(int id, int face);                  /* face 0 top, 1 side, 2 bottom */
#endif
